# -*- coding: utf-8 -*-
# Generated by Django 1.11.2 on 2017-06-19 13:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JAXIdDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaxid', models.CharField(max_length=6, unique=True, verbose_name='JAXid')),
                ('parent_jaxid', models.CharField(default='', help_text="Parent ID string of source JAXid; or use 'received' for newly received samples,'pool' for pools of libraries.", max_length=9, verbose_name='Parent JAXid')),
                ('collab_id', models.TextField(help_text='Collaborator sample ID.', verbose_name='Collaborator ID')),
                ('entered_into_lims', models.BooleanField(default=False, verbose_name='Entered into LIMS')),
                ('external_data', models.BooleanField(default=False, help_text='(not sequenced here.)', verbose_name='External data')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'JAXid Detail Records',
            },
        ),
        migrations.CreateModel(
            name='NucleicAcidType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Nucleic acid type identifiying code.', max_length=20, unique=True)),
                ('details', models.TextField(help_text='Nucleic acid type detailed name.')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectCode',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Project ID code (4 chars).', max_length=4, unique=True)),
                ('details', models.TextField(help_text='Project type detailed name.', verbose_name='Name')),
            ],
            options={
                'verbose_name_plural': 'Projects',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='SampleType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Sample type identifiying code (2 chars).', max_length=2, unique=True)),
                ('details', models.TextField(help_text='Sample type detailed name.')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SequencingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='Sequence type identifiying code (1 char).', max_length=1, unique=True)),
                ('details', models.TextField(help_text='Sequencing type detailed name.')),
            ],
            options={
                'ordering': ['code'],
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='jaxiddetail',
            name='nucleic_acid_type',
            field=models.ForeignKey(default='Z', on_delete=django.db.models.deletion.CASCADE, to='id_generate.NucleicAcidType', to_field='code'),
        ),
        migrations.AddField(
            model_name='jaxiddetail',
            name='project_code',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_generate.ProjectCode', to_field='code'),
        ),
        migrations.AddField(
            model_name='jaxiddetail',
            name='sample_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_generate.SampleType', to_field='code'),
        ),
        migrations.AddField(
            model_name='jaxiddetail',
            name='sequencing_type',
            field=models.ForeignKey(default='Z', on_delete=django.db.models.deletion.CASCADE, to='id_generate.SequencingType', to_field='code'),
        ),
    ]
