# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 19:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jaxiddetail',
            name='nucleic_acid_type',
        ),
        migrations.RemoveField(
            model_name='jaxiddetail',
            name='project_code',
        ),
        migrations.RemoveField(
            model_name='jaxiddetail',
            name='sample_type',
        ),
        migrations.RemoveField(
            model_name='jaxiddetail',
            name='sequencing_type',
        ),
        migrations.DeleteModel(
            name='JAXIdDetail',
        ),
    ]
