# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 19:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0002_auto_20171127_1444'),
    ]

    operations = [
        migrations.CreateModel(
            name='JAXIdDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('jaxid', models.CharField(max_length=6, unique=True, verbose_name='JAXid')),
                ('parent_jaxid', models.CharField(default='', help_text="Parent ID string of source JAXid; or use 'received' for newly received samples,'pool' for pools of libraries.", max_length=9, verbose_name='Parent JAXid')),
                ('collab_id', models.TextField(help_text='Collaborator sample ID.', verbose_name='Collaborator ID')),
                ('entered_into_lims', models.BooleanField(default=False, verbose_name='Entered into LIMS')),
                ('external_data', models.BooleanField(default=False, help_text='(not sequenced here.)', verbose_name='External data')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('nucleic_acid_type', models.ForeignKey(default='Z', on_delete=django.db.models.deletion.CASCADE, to='id_generate.NucleicAcidType', to_field='code')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_generate.ProjectCode', to_field='code')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_generate.SampleType', to_field='code')),
                ('sequencing_type', models.ForeignKey(default='Z', on_delete=django.db.models.deletion.CASCADE, to='id_generate.SequencingType', to_field='code')),
            ],
            options={
                'verbose_name_plural': 'JAXid Detail Records',
            },
        ),
    ]
