# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-18 16:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0003_jaxiddetail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaxiddetail',
            name='parent_jaxid',
            field=models.CharField(default='', help_text="Parent ID string of source JAXid; or use 'RECD' for newly received samples,'POOL' for pools of libraries.", max_length=6, verbose_name='Parent JAXid'),
        ),
    ]
