# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-26 09:12
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0004_auto_20180118_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaxiddetail',
            name='jaxid',
            field=models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='JAXid'),
        ),
    ]
