# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 13:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0006_boxid'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='boxid',
            options={'verbose_name_plural': 'Box ID Records'},
        ),
    ]
