# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0007_auto_20180130_1337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='boxid',
            name='external_data',
        ),
    ]
