# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-30 13:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0008_remove_boxid_external_data'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxid',
            old_name='seq_type',
            new_name='sequencing_type',
        ),
    ]
