# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-01-31 09:57
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0009_auto_20180130_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='boxid',
            old_name='name',
            new_name='collab_id',
        ),
        migrations.RemoveField(
            model_name='boxid',
            name='boxid',
        ),
        migrations.RemoveField(
            model_name='boxid',
            name='nucleic_acid',
        ),
        migrations.RemoveField(
            model_name='boxid',
            name='parent_id',
        ),
        migrations.RemoveField(
            model_name='boxid',
            name='project',
        ),
        migrations.RemoveField(
            model_name='boxid',
            name='sample',
        ),
        migrations.AddField(
            model_name='boxid',
            name='jaxid',
            field=models.CharField(default='', max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='JAXid'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxid',
            name='nucleic_acid_type',
            field=models.ForeignKey(default='Z', on_delete=django.db.models.deletion.CASCADE, to='id_generate.NucleicAcidType', to_field='code'),
        ),
        migrations.AddField(
            model_name='boxid',
            name='parent_jaxid',
            field=models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Parent ID'),
        ),
        migrations.AddField(
            model_name='boxid',
            name='project_code',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='id_generate.ProjectCode', to_field='code'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='boxid',
            name='sample_type',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='id_generate.SampleType', to_field='code'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='boxid',
            name='sequencing_type',
            field=models.ForeignKey(default='Z', on_delete=django.db.models.deletion.CASCADE, to='id_generate.SequencingType', to_field='code'),
        ),
    ]
