# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 11:02
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0012_auto_20180131_1206'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlateId',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_jaxid', models.CharField(blank=True, default='', max_length=6, null=True, verbose_name='Parent ID')),
                ('collab_id', models.TextField(verbose_name='Name')),
                ('notes', models.TextField(blank=True, null=True, verbose_name='Notes')),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('jaxid', models.CharField(max_length=6, unique=True, validators=[django.core.validators.MinLengthValidator(6)], verbose_name='Plate ID')),
                ('nucleic_acid_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_generate.NucleicAcidType', to_field='code', verbose_name='Nucleic Acid')),
                ('project_code', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_generate.ProjectCode', to_field='code', verbose_name='Project')),
                ('sample_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_generate.SampleType', to_field='code', verbose_name='Sample')),
                ('sequencing_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='id_generate.SequencingType', to_field='code')),
            ],
            options={
                'verbose_name_plural': 'Plate ID Records',
                'abstract': False,
            },
        ),
    ]
