# -*- coding: utf-8 -*-
# Generated by Django 1.11.9 on 2018-02-01 13:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0005_auto_20180130_0927'),
        ('id_generate', '0013_plateid'),
    ]

    operations = [
    ]
