# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 15:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0051_auto_20170403_1421'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jaxiddetail',
            options={'verbose_name_plural': 'JAXid Detail Records'},
        ),
        migrations.AlterField(
            model_name='jaxiddetail',
            name='entered_into_lims',
            field=models.BooleanField(default=False, verbose_name='Entered into LIMS'),
        ),
        migrations.AlterField(
            model_name='jaxiddetail',
            name='external_data',
            field=models.BooleanField(default=False, help_text='(not sequenced here.)', verbose_name='External data'),
        ),
    ]
