# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-19 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0052_auto_20170419_1108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaxiddetail',
            name='jaxid',
            field=models.CharField(max_length=6, unique=True, verbose_name='JAXid'),
        ),
    ]
