# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 13:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0053_auto_20170419_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaxiddetail',
            name='notes',
            field=models.TextField(blank=True, null=True, verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='jaxiddetail',
            name='nucleic_acid_type',
            field=models.ForeignKey(default='Z', on_delete=django.db.models.deletion.CASCADE, to='id_generate.NucleicAcidType', to_field='code'),
        ),
        migrations.AlterField(
            model_name='jaxiddetail',
            name='parent_jaxid',
            field=models.CharField(blank=True, default='', help_text='Parent ID string or leave blank if has no parent; RECVD for newly received samples.', max_length=6, verbose_name='Parent JAXid'),
        ),
        migrations.AlterField(
            model_name='jaxiddetail',
            name='sequencing_type',
            field=models.ForeignKey(default='Z', on_delete=django.db.models.deletion.CASCADE, to='id_generate.SequencingType', to_field='code'),
        ),
    ]
