# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-04-28 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0054_auto_20170428_0920'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='nucleicacidtype',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='projectcode',
            options={'ordering': ['code']},
        ),
        migrations.AlterModelOptions(
            name='sampletype',
            options={'ordering': ['code']},
        ),
    ]
