# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 14:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0055_auto_20170428_1608'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseRefClass',
        ),
        migrations.AlterModelOptions(
            name='sequencingtype',
            options={'ordering': ['code']},
        ),
    ]
