# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0057_auto_20170503_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nucleicacidtype',
            name='details',
            field=models.TextField(help_text='Nucleic acid type detailed name.'),
        ),
        migrations.AlterField(
            model_name='sampletype',
            name='details',
            field=models.TextField(help_text='Sample type detailed name.'),
        ),
        migrations.AlterField(
            model_name='sequencingtype',
            name='details',
            field=models.TextField(help_text='Sequencing type detailed name.'),
        ),
    ]
