# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0058_auto_20170503_1200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectcode',
            name='code',
            field=models.CharField(help_text='Project ID code (4 chars).', max_length=4, unique=True, verbose_name='Code'),
        ),
        migrations.AlterField(
            model_name='projectcode',
            name='details',
            field=models.TextField(help_text='Project type detailed name.', verbose_name='Name'),
        ),
    ]
