# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 16:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0060_auto_20170503_1204'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectcode',
            options={'ordering': ['code'], 'verbose_name_plural': 'Projects'},
        ),
    ]
