# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-03 17:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('id_generate', '0061_auto_20170503_1209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jaxiddetail',
            name='sample_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='id_generate.SampleType', to_field='code'),
        ),
    ]
